In [1]:
import pandas as pd
import numpy as np

In [2]:
pip install pandas openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/valeriia/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: openpyxl in /Users/valeriia/Library/Python/3.9/lib/python/site-packages (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/valeriia/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/valeriia/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: numpy>=1.22.4 in /Users/valeriia/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/valeriia/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.2)
Requirement already satisfied: et-xmlfile in /Users/valeriia/Library/Python/3.9/lib/python/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [6]:
sales_2024 = pd.read_excel(
    "/Users/valeriia/Desktop/Ala-Tash DA/Строительные материалы 2024.xlsm",
    sheet_name="Статистика"
)

sales_2025 = pd.read_excel(
    "/Users/valeriia/Desktop/Ala-Tash DA/Строительные материалы 2025.xlsm",
    sheet_name="Статистика"
)

sales_2026 = pd.read_excel(
    "/Users/valeriia/Desktop/Ala-Tash DA/Строительные материалы 2026.xlsm",
    sheet_name="Статистика"
)

datasets = {
    2024: sales_2024,
    2025: sales_2025,
    2026: sales_2026
}

cleaned_datasets = []

for year, df in datasets.items():

    # Очищаем названия столбцов
    df.columns = (
        df.columns
        .astype(str)
        .str.replace("\n", " ", regex=False)
        .str.replace("\r", " ", regex=False)
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

    # Удаляем только первый служебный № п.п., если он находится
    # среди основных колонок
    df = df.drop(columns=["№ п.п."], errors="ignore")

    # Добавляем год
    df["Год"] = year

    # Номер заказа сохраняем как текст
    df["№ заказа"] = df["№ заказа"].astype(str).str.strip()

    # Создаем уникальный ключ
    df["Order_ID"] = (
        df["Год"].astype(str)
        + "_"
        + df["№ заказа"]
    )

    cleaned_datasets.append(df)

sales_master = pd.concat(
    cleaned_datasets,
    ignore_index=True
)

print(sales_master.shape)
print(sales_master[["Год", "№ заказа", "Order_ID"]].head())

print(sales_master.shape)
print(sales_master.columns[:20].tolist())

(49699, 208)
    Год № заказа  Order_ID
0  2024      0,1  2024_0,1
1  2024      0,2  2024_0,2
2  2024      0,3  2024_0,3
3  2024      0,4  2024_0,4
4  2024      0,5  2024_0,5
(49699, 208)
['№ заказа', 'Анкета', 'Ф.И.О.', 'Телефоны', 'Установщик', 'Принят', 'Оговорено', 'Отпущен', 'Сумма, сом', 'Скидка, сом', 'Со скидкой', 'Авансы', 'Остаток', 'Долг', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19']

In [9]:
import os

print(os.getcwd())
print(os.listdir())

/Users/valeriia/Desktop/PhytonDA7/base
['Ala_tash.ipynb', 'Sales_validation.ipynb']

In [11]:
df = pd.read_excel(
    "/Users/valeriia/Desktop/Ala-Tash DA/Строительные материалы 2024.xlsm",
    sheet_name="Статистика"
)

print(df.columns.tolist())

['№\nзаказа', 'Анкета', 'Ф.И.О.', 'Телефоны', 'Установщик', 'Принят', 'Оговорено', 'Отпущен', 'Сумма, сом', 'Скидка, сом', 'Со скидкой', 'Авансы', 'Остаток', 'Долг', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114', 'Unnamed: 115', 'Unnamed: 116', 'Unnamed: 117', 'Unnamed: 118', 'Unnamed: 119', 'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', '№ п.п.', 'Наименование', 'Ед. измер.', 'Кол-во', 'Цена, сом', 'Цена со скидкой, сом', 'Сумма, сом.1', 'Сумма со скидкой, сом', '№ п.п..1', 'Наименование.1', 'Ед. измер..1', 'Кол-во.1', 'Цена, сом.1', 'Цена со скидкой, сом.1', 'Сумма, сом.2', 'Сумма со скидкой, сом.1', '№ п.п..2', 'Наименование.2', 'Ед. измер..2', 'Кол-во.2', 'Цена, сом.2', 'Цена со скидкой, сом.2', 'Сумма, сом.3', 'Сумма со скидкой, сом.2', '№ п.п..3', 'Наименование.3', 'Ед. измер..3', 'Кол-во.3', 'Цена, сом.3', 'Цена со скидкой, сом.3', 'Сумма, сом.4', 'Сумма со скидкой, сом.3', '№ п.п..4', 'Наименование.4', 'Ед. измер..4', 'Кол-во.4', 'Цена, сом.4', 'Цена со скидкой, сом.4', 'Сумма, сом.5', 'Сумма со скидкой, сом.4', '№ п.п..5', 'Наименование.5', 'Ед. измер..5', 'Кол-во.5', 'Цена, сом.5', 'Цена со скидкой, сом.5', 'Сумма, сом.6', 'Сумма со скидкой, сом.5', '№ п.п..6', 'Наименование.6', 'Ед. измер..6', 'Кол-во.6', 'Цена, сом.6', 'Цена со скидкой, сом.6', 'Сумма, сом.7', 'Сумма со скидкой, сом.6', '№ п.п..7', 'Наименование.7', 'Ед. измер..7', 'Кол-во.7', 'Цена, сом.7', 'Цена со скидкой, сом.7', 'Сумма, сом.8', 'Сумма со скидкой, сом.7', '№ п.п..8', 'Наименование.8', 'Ед. измер..8', 'Кол-во.8', 'Цена, сом.8', 'Цена со скидкой, сом.8', 'Сумма, сом.9', 'Сумма со скидкой, сом.8', '№ п.п..9', 'Наименование.9', 'Ед. измер..9', 'Кол-во.9', 'Цена, сом.9', 'Цена со скидкой, сом.9', 'Сумма, сом.10', 'Сумма со скидкой, сом.9']

In [12]:
import pandas as pd
import numpy as np

files = {
    2024: "/Users/valeriia/Desktop/Ala-Tash DA/Строительные материалы 2024.xlsm",
    2025: "/Users/valeriia/Desktop/Ala-Tash DA/Строительные материалы 2025.xlsm",
    2026: "/Users/valeriia/Desktop/Ala-Tash DA/Строительные материалы 2026.xlsm"
}

order_columns = [
    "№ заказа",
    "Анкета",
    "Ф.И.О.",
    "Телефоны",
    "Установщик",
    "Принят",
    "Оговорено",
    "Отпущен",
    "Сумма, сом",
    "Скидка, сом",
    "Со скидкой",
    "Авансы",
    "Остаток",
    "Долг"
]

orders_list = []
items_list = []

for year, file_path in files.items():

    df = pd.read_excel(
        file_path,
        sheet_name="Статистика",
        engine="openpyxl"
    )

    # Очищаем переносы строк и лишние пробелы в названиях
    df.columns = (
        df.columns
        .astype(str)
        .str.replace("\n", " ", regex=False)
        .str.replace("\r", " ", regex=False)
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )

    # Оставляем только строки, где есть номер заказа
    df = df[df["№ заказа"].notna()].copy()

    # Номер заказа сохраняем как текст
    df["№ заказа"] = (
        df["№ заказа"]
        .astype(str)
        .str.strip()
    )

    df["Год"] = year

    # Уникальный ключ: год + номер заказа
    df["Order_ID"] = (
        df["Год"].astype(str)
        + "_"
        + df["№ заказа"]
    )

    # Таблица заказов
    orders_year = df[order_columns + ["Год", "Order_ID"]].copy()

    orders_list.append(orders_year)

     # В файле предусмотрено до 10 товарных позиций
    for position in range(10):

        # Для первой позиции суффикса нет
        suffix = "" if position == 0 else f".{position}"

        name_col = f"Наименование{suffix}"
        unit_col = f"Ед. измер.{suffix}" if position > 0 else "Ед. измер."
        qty_col = f"Кол-во{suffix}"
        price_col = f"Цена, сом{suffix}"
        discounted_price_col = (
            f"Цена со скидкой, сом{suffix}"
        )

        # У столбцов суммы особая нумерация:
        # первая товарная сумма называется "Сумма, сом.1"
        sum_number = position + 1
        sum_col = f"Сумма, сом.{sum_number}"

        discounted_sum_col = (
            "Сумма со скидкой, сом"
            if position == 0
            else f"Сумма со скидкой, сом.{position}"
        )

        required_columns = [
            name_col,
            unit_col,
            qty_col,
            price_col,
            discounted_price_col,
            sum_col,
            discounted_sum_col
        ]

        # Проверяем наличие блока в конкретном файле
        if not all(col in df.columns for col in required_columns):
            print(
                f"{year}: пропущен блок позиции {position + 1}, "
                "не все столбцы найдены"
            )
            continue

        item_block = df[
            ["Order_ID", "Год", "№ заказа"] + required_columns
        ].copy()

        item_block.columns = [
            "Order_ID",
            "Год",
            "№ заказа",
            "Наименование",
            "Ед. измер.",
            "Кол-во",
            "Цена, сом",
            "Цена со скидкой, сом",
            "Сумма позиции, сом",
            "Сумма позиции со скидкой, сом"
        ]

        item_block["Позиция"] = position + 1

        # Оставляем строки, где действительно указано наименование
        item_block = item_block[
            item_block["Наименование"].notna()
        ].copy()

        items_list.append(item_block)

        sales_orders = pd.concat(
    orders_list,
    ignore_index=True
)

sales_items = pd.concat(
    items_list,
    ignore_index=True
)

print("Таблица заказов:", sales_orders.shape)
print("Таблица товарных позиций:", sales_items.shape)

print(
    sales_orders.groupby("Год")
    .size()
)
print(
    sales_items.groupby("Год")
    .size()
)

sales_items.head(20)

sales_items[
    sales_items["Order_ID"] == "2024_0,1"
]

order_numeric_columns = [
    "Сумма, сом",
    "Скидка, сом",
    "Со скидкой",
    "Авансы",
    "Остаток",
    "Долг"
]

for col in order_numeric_columns:
    sales_orders[col] = pd.to_numeric(
        sales_orders[col],
        errors="coerce"
    )

item_numeric_columns = [
    "Кол-во",
    "Цена, сом",
    "Цена со скидкой, сом",
    "Сумма позиции, сом",
    "Сумма позиции со скидкой, сом"
]

for col in item_numeric_columns:
    sales_items[col] = pd.to_numeric(
        sales_items[col],
        errors="coerce"
    )

date_columns = [
    "Принят",
    "Оговорено",
    "Отпущен"
]

for col in date_columns:
    sales_orders[col] = pd.to_datetime(
        sales_orders[col],
        errors="coerce"
    )
sales_orders.to_excel(
    "/Users/valeriia/Desktop/Ala-Tash DA/Sales_Orders_Master.xlsx",
    index=False
)

sales_items.to_excel(
    "/Users/valeriia/Desktop/Ala-Tash DA/Sales_Items_Master.xlsx",
    index=False
)

Таблица заказов: (3758, 16)
Таблица товарных позиций: (8512, 11)
Год
2024    1686
2025    1398
2026     674
dtype: int64
Год
2024    3796
2025    3443
2026    1273
dtype: int64

In [14]:
print(sales_orders.shape)
sales_orders.info()
sales_orders.head()
sales_orders.tail()

(3758, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3758 entries, 0 to 3757
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   № заказа     3758 non-null   object
 1   Анкета       468 non-null    object
 2   Ф.И.О.       3208 non-null   object
 3   Телефоны     2016 non-null   object
 4   Установщик   1479 non-null   object
 5   Принят       3213 non-null   datetime64[ns]
 6   Оговорено    3216 non-null   datetime64[ns]
 7   Отпущен      3135 non-null   datetime64[ns]
 8   Сумма, сом   3293 non-null   float64
 9   Скидка, сом  3294 non-null   float64
 10  Со скидкой   3294 non-null   float64
 11  Авансы       3295 non-null   float64
 12  Остаток      3295 non-null   float64
 13  Долг         3295 non-null   float64
 14  Год          3758 non-null   int64
 15  Order_ID     3758 non-null   object
dtypes: datetime64[ns](3), float64(6), int64(1), object(6)
memory usage: 469.9+ KB

,№ заказа,Анкета,Ф.И.О.,Телефоны,Установщик,Принят,Оговорено,Отпущен,"Сумма, сом","Скидка, сом",Со скидкой,Авансы,Остаток,Долг,Год,Order_ID
3753,6.70000000000004,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2026,2026_6.70000000000004
3754,6.71000000000004,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2026,2026_6.71000000000004
3755,6.72000000000004,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2026,2026_6.72000000000004
3756,6.73000000000004,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2026,2026_6.73000000000004
3757,6.74000000000004,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2026,2026_6.74000000000004

In [15]:
sales_orders.isna().sum()

№ заказа          0
Анкета         3290
Ф.И.О.          550
Телефоны       1742
Установщик     2279
Принят          545
Оговорено       542
Отпущен         623
Сумма, сом      465
Скидка, сом     464
Со скидкой      464
Авансы          463
Остаток         463
Долг            463
Год               0
Order_ID          0
dtype: int64

In [16]:
sales_orders.duplicated().sum()

np.int64(3)

In [17]:
sales_orders.groupby("Год").size()

Год
2024    1686
2025    1398
2026     674
dtype: int64

In [18]:
sales_orders.describe()

,Принят,Оговорено,Отпущен,"Сумма, сом","Скидка, сом",Со скидкой,Авансы,Остаток,Долг,Год
count,3213,3216,3135,3.293000e+03,3294.000000,3.294000e+03,3.295000e+03,3.295000e+03,3.295000e+03,3758.000000
mean,2025-02-17 16:51:59.327730944,2025-03-01 17:23:17.014925312,2025-01-28 15:59:32.440191488,5.239591e+04,1788.886208,5.059112e+04,4.913921e+04,1.436562e+03,1.449014e+03,2024.730708
min,1982-02-18 00:00:00,2012-07-17 00:00:00,1900-01-27 00:00:00,0.000000e+00,0.000000,-5.000000e-01,0.000000e+00,-1.000000e+04,0.000000e+00,2024.000000
25%,2024-07-15 00:00:00,2024-07-26 00:00:00,2024-07-25 12:00:00,1.012800e+04,0.000000,9.890750e+03,9.675000e+03,-2.000000e-01,0.000000e+00,2024.000000
50%,2025-02-18 00:00:00,2025-02-21 00:00:00,2025-02-21 00:00:00,2.199900e+04,0.000000,2.117375e+04,2.095000e+04,0.000000e+00,0.000000e+00,2025.000000
75%,2025-09-26 00:00:00,2025-09-30 06:00:00,2025-09-27 00:00:00,4.588688e+04,668.000000,4.481130e+04,4.436500e+04,0.000000e+00,0.000000e+00,2025.000000
max,2029-08-28 00:00:00,2029-05-29 00:00:00,2041-10-22 00:00:00,3.751367e+06,207234.000000,3.584417e+06,3.584417e+06,3.115200e+06,3.115200e+06,2026.000000
std,NaN,NaN,NaN,1.682367e+05,9351.185217,1.623523e+05,1.531795e+05,5.483550e+04,5.483445e+04,0.745401

In [19]:
sales_orders.nlargest(10, "Сумма, сом")

,№ заказа,Анкета,Ф.И.О.,Телефоны,Установщик,Принят,Оговорено,Отпущен,"Сумма, сом","Скидка, сом",Со скидкой,Авансы,Остаток,Долг,Год,Order_ID
2326,"6,41",NaN,Сапатжолстрой,NaN,Романенко А.,2025-06-26,2025-06-27,2025-07-27,3751367.0,166950.0,3584417.0,3584417.0,0.0,0.0,2025,"2025_6,41"
2022,"3,37",NaN,ОсОО Сапатжолстрой,NaN,Романенко А.,2025-04-11,2025-04-25,2025-04-25,3203083.0,133890.0,3069193.0,3069193.0,0.0,0.0,2025,"2025_3,37"
1632,"16,33",NaN,Чолпонкул Исаевич,995775577,Осьмак С.,2024-12-11,NaT,NaT,3115200.0,0.0,3115200.0,0.0,3115200.0,3115200.0,2024,"2024_16,33"
2140,"4,55",NaN,ОсОО Сапатжолстрой,NaN,Романенко А.,2025-05-22,2025-06-02,2025-05-16,2619328.0,116570.0,2502758.0,2502758.0,0.0,0.0,2025,"2025_4,55"
2077,"3,92",NaN,ОсОО Сапатжолстрой,NaN,Романенко А.,2025-04-28,2025-05-15,2025-05-15,2485835.0,95309.1,2390525.9,2390526.0,-0.1,0.0,2025,"2025_3,92"
2902,"12,17",NaN,Сапат Жол Строй,NaN,NaN,2025-11-12,2025-11-13,2025-11-13,2274690.0,0.0,2274690.0,2274690.0,0.0,0.0,2025,"2025_12,17"
2309,"6,24",NaN,Сапатжолстрой,NaN,Романенко А.,2025-06-24,2025-06-25,2025-07-17,1911074.0,85050.0,1826024.0,1826024.0,0.0,0.0,2025,"2025_6,24"
1080,"10,81",NaN,ОсОО Эталон Вин Спец Строй,772674303 Бахтияр,NaN,2024-08-12,2024-08-20,2024-08-30,1722120.0,0.0,1722120.0,1722120.0,0.0,0.0,2024,"2024_10,81"
2985,"12,99",NaN,Сапат Жол Строй,NaN,NaN,2025-12-08,2025-12-11,2025-12-11,1721180.0,0.0,1721180.0,1721180.0,0.0,0.0,2025,"2025_12,99"
1378,"13,79",NaN,Берикбаев Адилет,NaN,Шалдыбин А.,2024-10-11,2024-12-04,2024-12-04,1621452.0,50152.0,1571300.0,1571300.0,0.0,0.0,2024,"2024_13,79"

In [20]:
sales_clean = sales_orders.copy()

In [21]:
date_cols = ["Принят", "Оговорено", "Отпущен"]

for col in date_cols:
    sales_clean.loc[
        (sales_clean[col] < "2024-01-01") |
        (sales_clean[col] > "2026-06-30"),
        col
    ] = pd.NaT

In [23]:
sales_clean[
    sales_clean["Со скидкой"] < 0
]
sales_clean[
    sales_clean["Сумма, сом"] < 0
]
sales_clean[
    sales_clean["Остаток"] < 0
]

,№ заказа,Анкета,Ф.И.О.,Телефоны,Установщик,Принят,Оговорено,Отпущен,"Сумма, сом","Скидка, сом",Со скидкой,Авансы,Остаток,Долг,Год,Order_ID
1,"0,2",NaN,Митина Наталья,704505078,NaN,2024-01-04,2024-01-17,2024-01-18,12937.20,0.0,12937.20,12940.0,-2.80,0.0,2024,"2024_0,2"
9,"0,10",NaN,Мадалиев Хабиб,555847844,NaN,2024-01-09,2024-01-18,2024-01-19,38648.35,0.0,38648.35,39000.0,-351.65,0.0,2024,"2024_0,10"
14,"0,15",NaN,Венера,772662000,Николай,2024-01-16,2024-01-30,2024-01-26,73554.50,0.0,73554.50,73555.0,-0.50,0.0,2024,"2024_0,15"
18,"0,19",NaN,Токушова Джипара,555780170,NaN,2024-01-11,2024-01-18,2024-01-18,10936.00,1214.0,9722.00,10000.0,-278.00,0.0,2024,"2024_0,19"
28,"0,29",NaN,Ким Вероника,555651859,NaN,2024-01-15,2024-01-26,2024-03-22,91892.00,0.0,91892.00,94657.0,-2765.00,0.0,2024,"2024_0,29"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3673,"5,90",NaN,Камила,NaN,Николай,2026-06-23,2026-06-30,2026-06-30,21780.70,0.0,21780.70,21800.0,-19.30,0.0,2026,"2026_5,90"
3676,"5,93",NaN,Асылбек,703283183,NaN,NaT,NaT,NaT,33339.30,0.0,33339.30,34960.0,-1620.70,0.0,2026,"2026_5,93"
3680,"5,97",NaN,Сергеев Андрей,NaN,NaN,2026-06-23,2026-06-24,NaT,5544.00,0.0,5544.00,5550.0,-6.00,0.0,2026,"2026_5,97"
3688,"6,5",NaN,заказчик,NaN,Николай,2026-06-24,NaT,2026-06-29,20096.80,0.0,20096.80,20097.0,-0.20,0.0,2026,"2026_6,5"
3695,"6,12",NaN,Кылычов Рахман,705277142,NaN,2026-06-25,NaT,NaT,39205.70,1206.0,37999.70,38000.0,-0.30,0.0,2026,"2026_6,12"

In [25]:
sales_orders["Сумма, сом"].describe()
sales_orders.nlargest(10, "Сумма, сом")[
    [
        "Order_ID",
        "Ф.И.О.",
        "Сумма, сом",
        "Год"
    ]
]
sales_orders["Проверка"] = (
    sales_orders["Сумма, сом"]
    - sales_orders["Скидка, сом"]
).round(2)

sales_orders[
    (
        sales_orders["Проверка"]
        != sales_orders["Со скидкой"].round(2)
    )
]

,№ заказа,Анкета,Ф.И.О.,Телефоны,Установщик,Принят,Оговорено,Отпущен,"Сумма, сом","Скидка, сом",Со скидкой,Авансы,Остаток,Долг,Год,Order_ID,Проверка
20,0.21,отмена,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2024,2024_0.21,NaN
22,0.23,отмена,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2024,2024_0.23,NaN
31,0.32,отмена,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2024,2024_0.32,NaN
32,0.33,отмена,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2024,2024_0.33,NaN
45,0.46,отмена,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2024,2024_0.46,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3753,6.70000000000004,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2026,2026_6.70000000000004,NaN
3754,6.71000000000004,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2026,2026_6.71000000000004,NaN
3755,6.72000000000004,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2026,2026_6.72000000000004,NaN
3756,6.73000000000004,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2026,2026_6.73000000000004,NaN
3757,6.74000000000004,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2026,2026_6.74000000000004,NaN

In [26]:
check_discount = sales_orders[
    sales_orders["Сумма, сом"].notna()
].copy()

check_discount["Проверка"] = (
    check_discount["Сумма, сом"]
    - check_discount["Скидка, сом"]
).round(2)

errors = check_discount[
    check_discount["Проверка"]
    != check_discount["Со скидкой"].round(2)
]

print(errors.shape)
errors.head()

(2, 17)

,№ заказа,Анкета,Ф.И.О.,Телефоны,Установщик,Принят,Оговорено,Отпущен,"Сумма, сом","Скидка, сом",Со скидкой,Авансы,Остаток,Долг,Год,Order_ID,Проверка
228,"2,29",NaN,Шафигулин Радик,554301098,NaN,2024-03-04,2024-03-14,2024-03-07,52014.5,15.0,52014.5,52000.0,14.5,0.0,2024,"2024_2,29",51999.5
2001,"3,16",NaN,Капарова Назгуль,701999121,NaN,2025-04-09,2025-04-11,2025-04-11,3048.0,NaN,3048.0,3100.0,-52.0,0.0,2025,"2025_3,16",NaN

In [28]:
sales = sales_orders.copy()
sales["Статус заказа"] = "Активный"

sales.loc[
    sales["Анкета"] == "отмена",
    "Статус заказа"
] = "Отменен"
sales_valid = sales[
    sales["Сумма, сом"].notna()
].copy()
print(sales.shape)
print(sales_valid.shape)
sales["Статус заказа"].value_counts(dropna=False)

(3758, 18)
(3293, 18)

Статус заказа
Активный    3427
Отменен      331
Name: count, dtype: int64

In [29]:
cancel_rate = (
    sales["Статус заказа"]
    .value_counts(normalize=True) * 100
).round(2)

print(cancel_rate)

Статус заказа
Активный    91.19
Отменен      8.81
Name: proportion, dtype: float64

In [30]:
kpi = pd.DataFrame({
    "Метрика": [
        "Количество заказов",
        "Активные заказы",
        "Отмененные заказы",
        "Общая выручка",
        "Средний чек",
        "Медианный чек",
        "Максимальный чек",
        "Минимальный чек"
    ],
    "Значение": [
        len(sales),
        len(sales_valid),
        len(sales) - len(sales_valid),
        sales_valid["Сумма, сом"].sum(),
        sales_valid["Сумма, сом"].mean(),
        sales_valid["Сумма, сом"].median(),
        sales_valid["Сумма, сом"].max(),
        sales_valid["Сумма, сом"].min()
    ]
})

kpi

              Метрика      Значение
0  Количество заказов  3.758000e+03
1     Активные заказы  3.293000e+03
2   Отмененные заказы  4.650000e+02
3       Общая выручка  1.725397e+08
4         Средний чек  5.239591e+04
5       Медианный чек  2.199900e+04
6    Максимальный чек  3.751367e+06
7     Минимальный чек  0.000000e+00

In [31]:
total_orders = len(sales)

active_orders = (sales["Статус заказа"] == "Активный").sum()

cancelled_orders = (sales["Статус заказа"] == "Отменен").sum()

cancel_rate = round(cancelled_orders / total_orders * 100, 2)

In [32]:
sales_valid[sales_valid["Сумма, сом"] == 0]

,№ заказа,Анкета,Ф.И.О.,Телефоны,Установщик,Принят,Оговорено,Отпущен,"Сумма, сом","Скидка, сом",Со скидкой,Авансы,Остаток,Долг,Год,Order_ID,Проверка,Статус заказа
6,"0,7",отмена,NaN,NaN,NaN,NaT,NaT,NaT,0.0,0.0,0.0,0.0,0.0,0.0,2024,"2024_0,7",0.0,Отменен
27,"0,28",отмена,отмена,NaN,NaN,NaT,NaT,NaT,0.0,0.0,0.0,0.0,0.0,0.0,2024,"2024_0,28",0.0,Отменен
97,"0,98",NaN,З.И.,NaN,NaN,NaT,NaT,2024-02-01,0.0,0.0,0.0,0.0,0.0,0.0,2024,"2024_0,98",0.0,Активный
214,"2,15",без оплаты,Алла (З.И.),NaN,NaN,NaT,NaT,NaT,0.0,0.0,0.0,0.0,0.0,0.0,2024,"2024_2,15",0.0,Активный
420,"4,21",отмена,NaN,NaN,NaN,NaT,NaT,NaT,0.0,0.0,0.0,0.0,0.0,0.0,2024,"2024_4,21",0.0,Отменен
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3335,"2,52",NaN,Дооталиев Эмиль,557948080,NaN,2026-03-25,NaT,NaT,0.0,0.0,0.0,10000.0,-10000.0,0.0,2026,"2026_2,52",0.0,Активный
3346,"2,63",отмена,NaN,NaN,NaN,NaT,NaT,NaT,0.0,0.0,0.0,0.0,0.0,0.0,2026,"2026_2,63",0.0,Отменен
3448,"3,65",NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.0,0.0,0.0,0.0,0.0,0.0,2026,"2026_3,65",0.0,Активный
3464,"3,81",отмена,NaN,NaN,NaN,NaT,NaT,NaT,0.0,0.0,0.0,0.0,0.0,0.0,2026,"2026_3,81",0.0,Отменен
3513,"4,30",отмена,NaN,NaN,NaN,NaT,NaT,NaT,0.0,0.0,0.0,0.0,0.0,0.0,2026,"2026_4,30",0.0,Отменен

In [33]:
year_summary = (
    sales_valid
    .groupby("Год")
    .agg(
        Заказы=("Order_ID", "count"),
        Выручка=("Сумма, сом", "sum"),
        Средний_чек=("Сумма, сом", "mean"),
        Медианный_чек=("Сумма, сом", "median"),
        Сумма_скидок=("Скидка, сом", "sum")
    )
    .round(2)
)

year_summary

      Заказы      Выручка  Средний_чек  Медианный_чек  Сумма_скидок
Год
2024    1522  75109950.50     49349.51       20674.55    2058561.45
2025    1265  76781628.82     60696.94       22958.40    3024424.72
2026     506  20648160.80     40806.64       21640.55     809605.00

In [34]:
year_summary = (
    sales_valid
    .groupby("Год")
    .agg(
        Заказы=("Order_ID", "count"),
        Выручка=("Сумма, сом", "sum"),
        Средний_чек=("Сумма, сом", "mean"),
        Медианный_чек=("Сумма, сом", "median"),
        Максимальный_чек=("Сумма, сом", "max"),
        Сумма_скидок=("Скидка, сом", "sum"),
        Средняя_скидка=("Скидка, сом", "mean")
    )
    .round(2)
)

year_summary

,Заказы,Выручка,Средний_чек,Медианный_чек,Максимальный_чек,Сумма_скидок,Средняя_скидка
Год,,,,,,,
2024,1522,75109950.50,49349.51,20674.55,3115200.0,2058561.45,1352.54
2025,1265,76781628.82,60696.94,22958.40,3751367.0,3024424.72,2392.74
2026,506,20648160.80,40806.64,21640.55,1605912.0,809605.00,1600.01

In [35]:
monthly_orders = (
    sales_valid
    .groupby(["Год", sales_valid["Принят"].dt.month])
    .agg(
        Заказы=("Order_ID", "count"),
        Выручка=("Сумма, сом", "sum")
    )
)

monthly_orders

             Заказы       Выручка
Год  Принят
2024 1.0         77  3.873300e+06
     2.0        112  4.295087e+06
     3.0         95  4.834092e+06
     4.0        144  6.022116e+06
     5.0        153  8.097530e+06
     6.0        128  6.062392e+06
     7.0        179  1.098927e+07
     8.0        151  8.082677e+06
     9.0        121  4.545064e+06
     10.0       128  7.260567e+06
     11.0       101  4.193784e+06
     12.0        99  6.437410e+06
2025 1.0         69  2.624680e+06
     2.0         79  3.584508e+06
     3.0         89  4.058035e+06
     4.0        113  1.013576e+07
     5.0        105  9.892013e+06
     6.0        139  1.453142e+07
     7.0        126  7.273608e+06
     8.0        112  4.235424e+06
     9.0        103  4.936882e+06
     10.0       105  4.155278e+06
     11.0       101  6.521498e+06
     12.0        93  4.779769e+06
2026 1.0         59  1.658749e+06
     2.0         71  2.602631e+06
     3.0         93  3.951876e+06
     4.0        102  4.503548e+06
     5.0         98  5.818760e+06
     6.0         66  2.075930e+06
     9.0          1  5.641400e+03
     12.0         1  6.596000e+03

In [36]:
sales_valid[
    sales_valid["Принят"].dt.month.isin([9,12])
][["Order_ID","Принят","Ф.И.О.","Сумма, сом"]]

        Order_ID     Принят              Ф.И.О.  Сумма, сом
0       2024_0,1 2023-12-30       Авангард Сити     21176.0
728    2024_7,29 2024-09-05               Зулай     39521.4
1056  2024_10,57 2024-09-18           Валентина     76699.0
1070  2024_10,71 2024-09-05           Александр     72850.0
1082  2024_10,83 2024-09-17              Данияр     60914.0
...          ...        ...                 ...         ...
3080  2025_13,94 2025-12-29  Алексей Дмитриевич     38758.6
3081  2025_13,95 2025-12-29               Батыр     65066.6
3082  2025_13,96 2025-12-30               Борис      5593.0
3084    2026_0,1 2026-12-09               Эмиль      6596.0
3369   2026_2,86 2026-09-04        Ершов Сергей      5641.4

[418 rows x 4 columns]

In [37]:
sales_valid["Принят"].dt.year.value_counts().sort_index()

Принят
1982.0       1
2002.0       2
2005.0       1
2020.0       1
2023.0       2
2024.0    1478
2025.0    1234
2026.0     488
2027.0       2
2028.0       3
2029.0       1
Name: count, dtype: int64

In [38]:
sales_valid["Принят"].sort_values().head(20)

2856   1982-02-18
956    2002-07-23
1409   2002-10-18
1849   2005-02-24
819    2020-06-27
3676   2023-06-27
0      2023-12-30
1      2024-01-04
2      2024-01-05
5      2024-01-08
4      2024-01-08
8      2024-01-09
9      2024-01-09
10     2024-01-09
11     2024-01-09
7      2024-01-09
13     2024-01-10
16     2024-01-10
17     2024-01-10
12     2024-01-10
Name: Принят, dtype: datetime64[ns]

In [39]:
invalid_dates = sales_valid[
    (sales_valid["Принят"].dt.year < 2024) |
    (sales_valid["Принят"].dt.year > 2026)
]

invalid_dates[
    [
        "Order_ID",
        "Принят",
        "Ф.И.О.",
        "Сумма, сом",
        "Анкета"
    ]
].sort_values("Принят")

        Order_ID     Принят                   Ф.И.О.  Сумма, сом Анкета
2856  2025_11,71 1982-02-18                      NaN    41422.07    NaN
956    2024_9,57 2002-07-23                   Марьям    35640.00    NaN
1409  2024_14,10 2002-10-18  Посольство Азербайджана     3000.00    NaN
1849   2025_1,64 2005-02-24    Кондратенко Александр     8922.69    NaN
819    2024_8,20 2020-06-27                   Рустам    13671.00    NaN
3676   2026_5,93 2023-06-27                  Асылбек    33339.30    NaN
0       2024_0,1 2023-12-30            Авангард Сити    21176.00    NaN
353    2024_3,54 2027-04-03        Жунушалиева Сырга    31432.00    NaN
374    2024_3,75 2027-04-06         Акамбаева Айпери    26050.00    NaN
152    2024_1,53 2028-04-08                  Гульнур   120270.00   пам.
2063   2025_3,78 2028-04-28                Абдуразак     3619.00    NaN
2364   2025_6,79 2028-07-30                    Аслан    24156.00    NaN
2605   2025_9,20 2029-08-28       Сыдыкова Бактыгуль    38709.40    NaN

In [40]:
sales_clean = sales_valid.copy()

sales_clean.loc[
    (sales_clean["Принят"].dt.year < 2024) |
    (sales_clean["Принят"].dt.year > 2026),
    "Принят"
] = pd.NaT

In [41]:
sales_clean["Месяц"] = sales_clean["Принят"].dt.month

monthly_summary = (
    sales_clean
    .groupby(["Год", "Месяц"])
    .agg(
        Заказы=("Order_ID", "count"),
        Выручка=("Сумма, сом", "sum"),
        Средний_чек=("Сумма, сом", "mean"),
        Сумма_скидок=("Скидка, сом", "sum")
    )
    .round(2)
)

monthly_summary

            Заказы      Выручка  Средний_чек  Сумма_скидок
Год  Месяц
2024 1.0        77   3873300.39     50302.60     188317.80
     2.0       112   4295086.58     38348.99     192431.00
     3.0        95   4834091.97     50885.18     249761.00
     4.0       141   5844364.36     41449.39     171000.50
     5.0       153   8097529.86     52925.03     164787.00
     6.0       127   6048721.10     47627.73     170790.00
     7.0       178  10953631.61     61537.26     262636.00
     8.0       151   8082677.29     53527.66     141650.00
     9.0       121   4545064.28     37562.51      89333.00
     10.0      127   7257566.72     57146.19     168617.00
     11.0      101   4193783.88     41522.61     102188.00
     12.0       98   6416234.46     65471.78      57172.15
2025 1.0        69   2624679.66     38038.84      43363.00
     2.0        77   3534163.14     45898.22      60326.00
     3.0        89   4058035.04     45595.90     235469.00
     4.0       112  10132139.01     90465.53     352537.80
     5.0       105   9892013.47     94209.65     436426.00
     6.0       139  14531424.19    104542.62     822212.92
     7.0       125   7249452.24     57995.62     421963.00
     8.0       111   4196714.52     37808.24      95933.00
     9.0       103   4936882.05     47930.89     211698.00
     10.0      105   4155278.07     39574.08     136412.00
     11.0      101   6521498.49     64569.29      47149.00
     12.0       93   4779769.08     51395.37     157900.00
2026 1.0        59   1658749.32     28114.40      52551.00
     2.0        71   2602630.80     36656.77     121144.00
     3.0        93   3951875.63     42493.29     143729.00
     4.0       102   4503548.46     44152.44     115097.00
     5.0        98   5818759.66     59375.10     305138.00
     6.0        65   2042590.23     31424.47      69229.00
     9.0         1      5641.40      5641.40       1641.00
     12.0        1      6596.00      6596.00        596.00

In [42]:
top10_june2025 = (
    sales_valid[
        (sales_valid["Год"] == 2025) &
        (sales_valid["Принят"].dt.month == 6)
    ]
    .sort_values("Сумма, сом", ascending=False)
    .head(10)
)

top10_june2025[
    [
        "Ф.И.О.",
        "Сумма, сом",
        "Скидка, сом",
        "Со скидкой"
    ]
]

                  Ф.И.О.  Сумма, сом  Скидка, сом  Со скидкой
2326       Сапатжолстрой   3751367.0    166950.00  3584417.00
2309       Сапатжолстрой   1911074.0     85050.00  1826024.00
2229  ОсОО Сапатжолстрой   1340464.0    130432.12  1210031.88
2214               Канат    655590.0     55590.00   600000.00
2242     Аилчиев Саламат    512309.0     32309.00   480000.00
1706      Акынбаев Канат    401173.8     40297.80   360876.00
2273              Рустам    385690.0     15690.00   370000.00
2166           Ли Сергей    250714.0     25074.00   225640.00
2106       Акунова Жамал    239980.0         0.00   239980.00
2323   Кожокматов Данияр    218892.0      4892.00   214000.00

In [43]:
customer_revenue = (
    sales_valid
    .groupby("Ф.И.О.")
    .agg(
        Заказы=("Order_ID", "count"),
        Выручка=("Сумма, сом", "sum")
    )
    .sort_values("Выручка", ascending=False)
)

customer_revenue.head(20)

                            Заказы    Выручка
Ф.И.О.
ОсОО Сапатжолстрой               4  9648710.0
Сапатжолстрой                    2  5662441.0
Сапат Жол Строй                  2  3995870.0
Рузахунов Рузыбек               20  3458168.7
Романенко А.                     8  3271391.0
Чолпонкул Исаевич                1  3115200.0
Боотаев Азрет                   18  2984273.2
Аман                            10  2423718.0
Мазманов Я.С.                    3  2143426.5
Ли Сергей                       19  1919037.3
Аманов Сапар                     9  1789995.0
Зиньковский Федор                6  1752936.0
Кубан                            6  1740491.0
ОсОО Эталон Вин Спец Строй       1  1722120.0
Берикбаев Адилет                 1  1621452.0
Чудиев Нурлан                    3  1620504.0
ОсОО Мост Групп                  1  1589634.0
ОсОО Сапат Жол Строй             2  1548173.0
Шафигулин Радик                 22  1544878.8
Акынбаев Канат                  14  1530931.8

In [45]:
sales_clean = sales.copy()

# Оставляем сумму, клиента и другие данные,
# но очищаем неверные даты
mask = (
    (sales_clean["Принят"].dt.year < 2024) |
    (sales_clean["Принят"].dt.year > 2026)
)

sales_clean.loc[mask, "Принят"] = pd.NaT
sales_clean.to_excel(
    "/Users/valeriia/Desktop/Ala-Tash DA/sales_orders_clean.xlsx",
    index=False
)

In [46]:
import pandas as pd
import numpy as np

sales_clean = sales.copy()
mask = (
    (sales_clean["Принят"].dt.year < 2024) |
    (sales_clean["Принят"].dt.year > 2026)
)

sales_clean.loc[mask, "Принят"] = pd.NaT
sales_clean["Год_даты"] = sales_clean["Принят"].dt.year
sales_clean["Месяц_номер"] = sales_clean["Принят"].dt.month
months = {
    1:"Январь",
    2:"Февраль",
    3:"Март",
    4:"Апрель",
    5:"Май",
    6:"Июнь",
    7:"Июль",
    8:"Август",
    9:"Сентябрь",
    10:"Октябрь",
    11:"Ноябрь",
    12:"Декабрь"
}

sales_clean["Месяц"] = sales_clean["Месяц_номер"].map(months)
sales_clean["Квартал"] = sales_clean["Принят"].dt.quarter
sales_clean["Статус оплаты"] = np.select(
    [
        sales_clean["Остаток"] > 0,
        sales_clean["Остаток"] == 0,
        sales_clean["Остаток"] < 0
    ],
    [
        "Есть долг",
        "Оплачен",
        "Переплата"
    ],
    default="Нет данных"
)
sales_clean["Есть скидка"] = np.where(
    sales_clean["Скидка, сом"] > 0,
    "Да",
    "Нет"
)
sales_clean["Категория чека"] = pd.cut(
    sales_clean["Сумма, сом"],
    bins=[0,10000,30000,50000,100000,500000,10000000],
    labels=[
        "до 10 тыс.",
        "10–30 тыс.",
        "30–50 тыс.",
        "50–100 тыс.",
        "100–500 тыс.",
        "500 тыс.+"
    ]
)
sales_clean["Дней выполнения"] = (
    sales_clean["Отпущен"] -
    sales_clean["Принят"]
).dt.days
sales_clean.info()
sales_clean.head()
sales_clean.to_excel(
    "/Users/valeriia/Desktop/Ala-Tash DA/sales_orders_clean.xlsx",
    index=False
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3758 entries, 0 to 3757
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   № заказа         3758 non-null   object
 1   Анкета           468 non-null    object
 2   Ф.И.О.           3208 non-null   object
 3   Телефоны         2016 non-null   object
 4   Установщик       1479 non-null   object
 5   Принят           3200 non-null   datetime64[ns]
 6   Оговорено        3216 non-null   datetime64[ns]
 7   Отпущен          3135 non-null   datetime64[ns]
 8   Сумма, сом       3293 non-null   float64
 9   Скидка, сом      3294 non-null   float64
 10  Со скидкой       3294 non-null   float64
 11  Авансы           3295 non-null   float64
 12  Остаток          3295 non-null   float64
 13  Долг             3295 non-null   float64
 14  Год              3758 non-null   int64
 15  Order_ID         3758 non-null   object
 16  Проверка         3292 non-null   float64
 17  Статус заказа    3758 non-null   object
 18  Год_даты         3200 non-null   float64
 19  Месяц_номер      3200 non-null   float64
 20  Месяц            3200 non-null   object
 21  Квартал          3200 non-null   float64
 22  Статус оплаты    3758 non-null   object
 23  Есть скидка      3758 non-null   object
 24  Категория чека   3224 non-null   category
 25  Дней выполнения  3108 non-null   float64
dtypes: category(1), datetime64[ns](3), float64(11), int64(1), object(10)
memory usage: 738.0+ KB

In [48]:
sales_clean["Источник клиента"] = np.where(
    sales_clean["Анкета"].isin([
        "постоянный клиент",
        "через установщика"
    ]),
    sales_clean["Анкета"],
    "Не указан"
)
sales_clean["Тип оплаты"] = np.where(
    sales_clean["Анкета"]=="без оплаты",
    "Без оплаты",
    "Обычная продажа"
)

In [49]:
sales_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3758 entries, 0 to 3757
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   № заказа          3758 non-null   object
 1   Анкета            468 non-null    object
 2   Ф.И.О.            3208 non-null   object
 3   Телефоны          2016 non-null   object
 4   Установщик        1479 non-null   object
 5   Принят            3200 non-null   datetime64[ns]
 6   Оговорено         3216 non-null   datetime64[ns]
 7   Отпущен           3135 non-null   datetime64[ns]
 8   Сумма, сом        3293 non-null   float64
 9   Скидка, сом       3294 non-null   float64
 10  Со скидкой        3294 non-null   float64
 11  Авансы            3295 non-null   float64
 12  Остаток           3295 non-null   float64
 13  Долг              3295 non-null   float64
 14  Год               3758 non-null   int64
 15  Order_ID          3758 non-null   object
 16  Проверка          3292 non-null   float64
 17  Статус заказа     3758 non-null   object
 18  Год_даты          3200 non-null   float64
 19  Месяц_номер       3200 non-null   float64
 20  Месяц             3200 non-null   object
 21  Квартал           3200 non-null   float64
 22  Статус оплаты     3758 non-null   object
 23  Есть скидка       3758 non-null   object
 24  Категория чека    3224 non-null   category
 25  Дней выполнения   3108 non-null   float64
 26  Источник клиента  3758 non-null   object
 27  Тип оплаты        3758 non-null   object
dtypes: category(1), datetime64[ns](3), float64(11), int64(1), object(12)
memory usage: 796.7+ KB

In [51]:
sales_clean.drop(columns=["Проверка"], inplace=True)
sales_clean.drop(columns=["Телефоны"], inplace=True)
sales_clean["Месяц_Год"] = (
    sales_clean["Принят"]
    .dt.strftime("%Y-%m")
)
sales_clean["Скидка_%"] = np.where(
    sales_clean["Сумма, сом"] > 0,
    (
        sales_clean["Скидка, сом"] /
        sales_clean["Сумма, сом"] * 100
    ).round(2),
    0
)
sales_clean["Оплачен полностью"] = np.where(
    sales_clean["Остаток"] <= 0,
    "Да",
    "Нет"
)
sales_clean.info()
sales_clean.shape

KeyError: "['Проверка'] not found in axis"

In [52]:
for col in sales_clean.columns:
    print(col)

№ заказа
Анкета
Ф.И.О.
Установщик
Принят
Оговорено
Отпущен
Сумма, сом
Скидка, сом
Со скидкой
Авансы
Остаток
Долг
Год
Order_ID
Статус заказа
Год_даты
Месяц_номер
Месяц
Квартал
Статус оплаты
Есть скидка
Категория чека
Дней выполнения
Источник клиента
Тип оплаты
Месяц_Год

In [53]:
sales_clean["Дата_месяца"] = sales_clean["Принят"].dt.to_period("M").dt.to_timestamp()

In [54]:
sales_clean.to_excel(
    "/Users/valeriia/Desktop/Ala-Tash DA/sales_orders_master_v1.xlsx",
    index=False
)

In [55]:
for col in sales_orders.columns:
    print(col)

№ заказа
Анкета
Ф.И.О.
Телефоны
Установщик
Принят
Оговорено
Отпущен
Сумма, сом
Скидка, сом
Со скидкой
Авансы
Остаток
Долг
Год
Order_ID
Проверка

In [56]:
import pandas as pd

raw_2024 = pd.read_excel(
    "/Users/valeriia/Desktop/Ala-Tash DA/Строительные материалы 2024.xlsm",
    sheet_name="Статистика",
    engine="openpyxl"
)
for col in raw_2024.columns:
    print(col)
item_columns = [
    col for col in raw_2024.columns
    if (
        "Наименование" in str(col)
        or "Ед. измер" in str(col)
        or "Кол-во" in str(col)
        or "Цена" in str(col)
        or "Сумма со скидкой" in str(col)
        or str(col).startswith("№ п.п")
    )
]

for col in item_columns:
    print(col)
raw_2024[item_columns].dropna(how="all").head(10)
name_columns = [
    col for col in raw_2024.columns
    if "Наименование" in str(col)
]

raw_2024[name_columns].dropna(how="all").head(20)

№
заказа
Анкета
Ф.И.О.
Телефоны
Установщик
Принят
Оговорено
Отпущен
Сумма, сом
Скидка, сом
Со скидкой
Авансы
Остаток
Долг
Unnamed: 14
Unnamed: 15
Unnamed: 16
Unnamed: 17
Unnamed: 18
Unnamed: 19
Unnamed: 20
Unnamed: 21
Unnamed: 22
Unnamed: 23
Unnamed: 24
Unnamed: 25
Unnamed: 26
Unnamed: 27
Unnamed: 28
Unnamed: 29
Unnamed: 30
Unnamed: 31
Unnamed: 32
Unnamed: 33
Unnamed: 34
Unnamed: 35
Unnamed: 36
Unnamed: 37
Unnamed: 38
Unnamed: 39
Unnamed: 40
Unnamed: 41
Unnamed: 42
Unnamed: 43
Unnamed: 44
Unnamed: 45
Unnamed: 46
Unnamed: 47
Unnamed: 48
Unnamed: 49
Unnamed: 50
Unnamed: 51
Unnamed: 52
Unnamed: 53
Unnamed: 54
Unnamed: 55
Unnamed: 56
Unnamed: 57
Unnamed: 58
Unnamed: 59
Unnamed: 60
Unnamed: 61
Unnamed: 62
Unnamed: 63
Unnamed: 64
Unnamed: 65
Unnamed: 66
Unnamed: 67
Unnamed: 68
Unnamed: 69
Unnamed: 70
Unnamed: 71
Unnamed: 72
Unnamed: 73
Unnamed: 74
Unnamed: 75
Unnamed: 76
Unnamed: 77
Unnamed: 78
Unnamed: 79
Unnamed: 80
Unnamed: 81
Unnamed: 82
Unnamed: 83
Unnamed: 84
Unnamed: 85
Unnamed: 86
Unnamed: 87
Unnamed: 88
Unnamed: 89
Unnamed: 90
Unnamed: 91
Unnamed: 92
Unnamed: 93
Unnamed: 94
Unnamed: 95
Unnamed: 96
Unnamed: 97
Unnamed: 98
Unnamed: 99
Unnamed: 100
Unnamed: 101
Unnamed: 102
Unnamed: 103
Unnamed: 104
Unnamed: 105
Unnamed: 106
Unnamed: 107
Unnamed: 108
Unnamed: 109
Unnamed: 110
Unnamed: 111
Unnamed: 112
Unnamed: 113
Unnamed: 114
Unnamed: 115
Unnamed: 116
Unnamed: 117
Unnamed: 118
Unnamed: 119
Unnamed: 120
Unnamed: 121
Unnamed: 122
№ п.п.
Наименование
Ед. измер.
Кол-во
Цена, сом
Цена со скидкой, сом
Сумма, сом.1
Сумма со скидкой, сом
№ п.п..1
Наименование.1
Ед. измер..1
Кол-во.1
Цена, сом.1
Цена со скидкой, сом.1
Сумма, сом.2
Сумма со скидкой, сом.1
№ п.п..2
Наименование.2
Ед. измер..2
Кол-во.2
Цена, сом.2
Цена со скидкой, сом.2
Сумма, сом.3
Сумма со скидкой, сом.2
№ п.п..3
Наименование.3
Ед. измер..3
Кол-во.3
Цена, сом.3
Цена со скидкой, сом.3
Сумма, сом.4
Сумма со скидкой, сом.3
№ п.п..4
Наименование.4
Ед. измер..4
Кол-во.4
Цена, сом.4
Цена со скидкой, сом.4
Сумма, сом.5
Сумма со скидкой, сом.4
№ п.п..5
Наименование.5
Ед. измер..5
Кол-во.5
Цена, сом.5
Цена со скидкой, сом.5
Сумма, сом.6
Сумма со скидкой, сом.5
№ п.п..6
Наименование.6
Ед. измер..6
Кол-во.6
Цена, сом.6
Цена со скидкой, сом.6
Сумма, сом.7
Сумма со скидкой, сом.6
№ п.п..7
Наименование.7
Ед. измер..7
Кол-во.7
Цена, сом.7
Цена со скидкой, сом.7
Сумма, сом.8
Сумма со скидкой, сом.7
№ п.п..8
Наименование.8
Ед. измер..8
Кол-во.8
Цена, сом.8
Цена со скидкой, сом.8
Сумма, сом.9
Сумма со скидкой, сом.8
№ п.п..9
Наименование.9
Ед. измер..9
Кол-во.9
Цена, сом.9
Цена со скидкой, сом.9
Сумма, сом.10
Сумма со скидкой, сом.9
№ п.п.
Наименование
Ед. измер.
Кол-во
Цена, сом
Цена со скидкой, сом
Сумма со скидкой, сом
№ п.п..1
Наименование.1
Ед. измер..1
Кол-во.1
Цена, сом.1
Цена со скидкой, сом.1
Сумма со скидкой, сом.1
№ п.п..2
Наименование.2
Ед. измер..2
Кол-во.2
Цена, сом.2
Цена со скидкой, сом.2
Сумма со скидкой, сом.2
№ п.п..3
Наименование.3
Ед. измер..3
Кол-во.3
Цена, сом.3
Цена со скидкой, сом.3
Сумма со скидкой, сом.3
№ п.п..4
Наименование.4
Ед. измер..4
Кол-во.4
Цена, сом.4
Цена со скидкой, сом.4
Сумма со скидкой, сом.4
№ п.п..5
Наименование.5
Ед. измер..5
Кол-во.5
Цена, сом.5
Цена со скидкой, сом.5
Сумма со скидкой, сом.5
№ п.п..6
Наименование.6
Ед. измер..6
Кол-во.6
Цена, сом.6
Цена со скидкой, сом.6
Сумма со скидкой, сом.6
№ п.п..7
Наименование.7
Ед. измер..7
Кол-во.7
Цена, сом.7
Цена со скидкой, сом.7
Сумма со скидкой, сом.7
№ п.п..8
Наименование.8
Ед. измер..8
Кол-во.8
Цена, сом.8
Цена со скидкой, сом.8
Сумма со скидкой, сом.8
№ п.п..9
Наименование.9
Ед. измер..9
Кол-во.9
Цена, сом.9
Цена со скидкой, сом.9
Сумма со скидкой, сом.9

,Наименование,Наименование.1,Наименование.2,Наименование.3,Наименование.4,Наименование.5,Наименование.6,Наименование.7,Наименование.8,Наименование.9
0,Белая луна,фп,фаска,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Габбро,фмп,доставка,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Серая сталь,фп,калибровка,фп широкая,фаска 45,NaN,NaN,NaN,NaN,NaN
3,Серая волна,фп,калибровка,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Серая сталь,фп,калибровка,фаска,NaN,NaN,NaN,NaN,NaN,NaN
5,зеленый обож,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Эдельвейс,фаска,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Королевский,фп,доставка,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,габбро,фмп,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Лабрадорит коричневый,фмп,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Серая волна,фп,калибровка,фаска,NaN,NaN,NaN,NaN,NaN,NaN
12,Серая сталь,Распил криволинейный,фаска кривол,фаска фигурная,ФП,Доставка,NaN,NaN,NaN,NaN
13,Змеевик мр,фп фигурн,Кофе с молоком,калибровка,фаска,NaN,NaN,NaN,NaN,NaN
14,Серая сталь,фп,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Серая сталь,фмп,доставка,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Габбро,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Серая сталь,фп,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,малиновый,фп,доставка,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Эдельвейс,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Дымчастый,фп,калибровка,фаска 45,доставка,NaN,NaN,NaN,NaN,NaN